rm(list=ls())
library(pheatmap)
library("RColorBrewer")
library(tidyverse)
datax <- read_tsv("2.txt")
coldata <- as.data.frame(datax$GO_name)
datap <- select(datax,L,P,R,X,Class)
row.names(datap) <- datax$GO_name
go_levels <- c("Biological process","Cellular component","Molecular function")
datax$Class <- factor(datax$Class,levels = go_levels)
datap <- as.data.frame(datap,row.names = datax$GO_name)
annotation_row = data.frame(GO_levels = factor(rep(c("Biological process","Cellular component","Molecular function"),c(19,2,16))))
row.names(annotation_row) <- datax$GO_name
pheatmap(datap[,c(1,2,3,4)],cluster_cols = F,cluster_rows = F,scale = "row",annotation_row = annotation_row)
pheatmap(datap[,c(1,2,3,4)],cluster_cols = F,cluster_rows = F,annotation_row = annotation_row,gaps_row = c(19,21),border_color = "write")
p1=pheatmap(datap[,c(1,2,3,4)],cluster_cols = F,cluster_rows = F,annotation_row = annotation_row,gaps_row = c(19,21),color = colorRampPalette(rev(brewer.pal(n = 9, name = "Blues"))(10)))
require(Cairo)
Cairo( width = 2000, height = 2000,type="png",file="heatmap1.png",  bg = "white" , pointsize = 12, res=NA )
p1
dev.off()
